#version 450
#extension GL_GOOGLE_include_directive : require
#include "vulkanizer/shaders/svsm.glsl"
layout(local_size_x=32) in;
layout(std430,set=1,binding=0) buffer Results { vec2 results[]; };
void main() {
    uint i=gl_GlobalInvocationID.x;
    uint pixel=i%16u;
    vec3 position=vec3((float(pixel%4u)+0.5)*0.5-1.0,(float(pixel/4u)+0.5)*0.5-1.0,i<16u?0.75:0.1);
    results[i]=svsmSample(position,0.0);
}
